config/routes.rb
Myblog::Application.routes.draw do
  devise_for :users

  root 'blogs#index'

  resources :welcome do
    get 'index'
  end

  resources :articles do
  end

  resources :users do
    collection do
      get 'find'
      get 'login'
    end
  end

  resources :blogs do
  end

  resources :mobiles do

  end

  namespace :api do
    resources :articles
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  def author
    if user
      user.name
    else
      "unname"
    end
  end

  def user_avatar
    if user
      user.avatar
    else
      "/images/original/missing.png"
    end
  end

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  validates_presence_of :email

  has_many :articles

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/




end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController
  def index
    @articles = Article.order("created_at desc").page(params[:page]||1).per(params[:per]||5)

  end

end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
    # before_filter :response_json
    # response_to :json

  def articles
    @article = Article.all.page(params[:page]||1).per(params[:per]||5)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  before_filter :add_cors_headers

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :avatar
  end

  def add_cors_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET,OPTIONS'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #layout false
  before_action :authenticate_user!
  layout "admin_layout"


  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id=current_user.id
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def index

    @articles = Article.order("created_at desc").page(params[:page]||1).per(params[:per]||20)

  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.attributes = article_params
    if @article.save
      redirect_to articles_path(@article.user.id)
    else
      render 'edit'
    end
  end


  def show
    @article = Article.find(params[:id])
    # layout false
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end



  private
    def article_params
      params.require(:article).permit(:title, :description, :content, :tag, :user_id)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout 'blog_layout'

  def index
    @articles = Article.order("created_at desc")
  end

end

app/controllers/mobiles_controller.rb
class MobilesController < ApplicationController
  layout 'mobile_layout'
  def index
    @articles = Article.order("created_at desc")
  end

  # def show
  #   @article = Article.find(params[:id])
  # end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  layout "admin_layout"

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def index
    @users = User.order("created_at desc").page(params[:page]||1).per(params[:per]||10)
    @articles = Article.order("created_at desc").page(params[:page]||1).per(params[:per]||10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.attributes = user_params
    if @user.save
      redirect_to users_path
    else
      render 'edit'
    end
  end


  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end



  private
    def user_params
      params.require(:user).permit(:name, :email, :avatar, :password, :role)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/m_helper.rb
module MHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.slim
= form_for @article do |f|
  =@article.errors.messages
  .row
    .col-md-9
      .field
        p
          = f.label :title, '标题'
        p
          = f.text_field :title,:class=>"form-control"
      .field
        p
        = f.label :description, '简介'
        p
        = f.text_area :description,:class=>"form-control"
      .field
        p
        = f.label :content, '正文'
        p
        = f.kindeditor :content,:class=>"form-control"
    .col-md-3
      .field
        p
        = f.label :tag, '标签'
        p
        = f.text_area :tag,:class=>"form-control"
      .action
        = f.submit ' 提 交 ', :class=>'btn btn-primary'

end

app/views/articles/edit.slim
.container
  ol.breadcrumb
    li
      = link_to '首页','#'
    li
      = link_to '内容管理', '#'
    li.active
      = link_to '详情','#'


  .row
    .col-md-9
      = render :partial=>"form"
    .col-md-3

app/views/articles/index.slim
.container
  ol.breadcrumb
    li
      = link_to '首页','#'
    li.active
      = link_to '内容管理','#'

  .btn-group
    = link_to '写博客', new_article_path, :class => 'btn btn-primary'




    / .alist
    /   / = render :partial=>"article_list", :locals=>{:article=>Article.where(:user_id=>@user.id)}
    /   = render :partial=>"article_list", :locals=>{:articles=>@articles}
  .row
    .col-md-12
      table.table.table-responsive.table-hover
        thead
          th 标题
          th 摘要
          th 作者
          th 时间
          th 操作

        tbody
          - for article in @articles
            tr
              td = article.title
              td = article.description
              td = article.user.name
              td = article.created_at
              td
                = link_to '查看', article_path(article)
      .page
        =paginate @articles
      end

app/views/articles/new.slim
.container
  = render :partial=>'form'

app/views/articles/show.slim
.container
  ol.breadcrumb
    li
      = link_to '首页','#'
    li
      = link_to '内容管理','#'
    li.active
      = link_to '详情','#'


  .row
    .col-md-9
      .title
        h1 = @article.title
      .content
        = @article.content.html_safe
      p
        = @article.created_at

    .col-md-3
      .btn-group
        = button_to ' 编 辑 ', edit_article_path, method: :get, :class => 'btn btn-primary'

        = button_to ' 删 除 ', article_path, method: :delete, :class => 'btn btn-danger'

      h4
        |创建时间
      P
        = @article.created_at
      h4
        |更新时间
      p
        = @article.updated_at

app/views/blogs/index.slim
.list
  .listcontent
    -for article in @articles
      p
        = article.title

.indexbtngroup
  .icon-indexbtn


.scrollbar
  .ibtn
    .icon-arrow-up


  .ibtn
    .icon-arrow-down


.wrap
  .page-scroll
    - for article in @articles
      .page
        .title
          = article.title
        .content
          = article.content.html_safe



#mask
    /p
    /  = article.created_at
    /p
    /  = article.author
    /  = image_tag article.user_avatar, height:'20'

app/views/layouts/admin_layout.slim
html
  head
    =stylesheet_link_tag "bootstrap"
    =stylesheet_link_tag "admin"
    script src="/assets/kindeditor/kindeditor.js"
    = stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "admin", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          .navbar-brand
            =link_to '管理后台', '#'

        .navbar-collapse.collapse
          ul.nav.navbar-nav
            li
              = link_to '仪表盘','#'
            li
              = link_to '内容管理', articles_path
            li
              = link_to '用户管理', users_path
          ul.nav.navbar-nav.navbar-right
            li
              = link_to current_user.name, '#'
            li
              = link_to "注销", destroy_user_session_path




    .wrap
      =yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <div class='user'>
<% if user_signed_in? %>
<%= current_user.email %>
<%= link_to "logout", destroy_user_session_path %>
<% else %>
<%= link_to "login", new_user_session_path %>
<%= link_to "注册", new_user_registration_path %>
<% end %>
</div> -->

<%= yield %>

</body>
</html>

app/views/layouts/blog_layout.slim
html
  head
    =stylesheet_link_tag "blog"
    =stylesheet_link_tag "style"
    script src="/assets/jquery-2.1.0.min.js"
    script src="/assets/blog.js"
  body

    =yield

app/views/layouts/mobile_layout.slim
html
  head
    title Aidan的博客
    =stylesheet_link_tag "mobile"
    =stylesheet_link_tag "jquery.mobile-1.4.2"
    =stylesheet_link_tag "style"
    =favicon_link_tag 'favicon.ico'
    =favicon_link_tag 'mb-icon.png', rel: 'apple-touch-icon', type: 'image/png'
    script src="/assets/jquery-2.1.0.min.js"
    script src="/assets/jquery.mobile-1.4.2.min.js"
    script src="/assets/mobile.js"

    <link rel="apple-touch-startup-image" href="/images/startup-image.png">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="viewport" content="user-scalable=no" />

  body
    .statusbar
    =yield

app/views/mobiles/index.slim
.wrap
  .refresh
    .icon-refreshbtn

  .container
    .page-scroll
      / - for article in @articles
      - @articles.each_with_index do |article,index|
        .page data=index
          .title
            = article.title
          .content
            = article.content.html_safe

app/views/mobiles/show.slim
h1 show

app/views/users/_article_form.slim
= form_for article do |f|
  =article.errors.messages

  = f.hidden_field :user_id

  .field
    p
      = f.label :title, '标题'
    p
      = f.text_field :title,:class=>"form-control"

  .field
    p
    = f.label :description, '简介'
    p
    = f.text_area :description,:class=>"form-control"

  .field
    p
    = f.label :content, '正文'
    p
    = f.kindeditor :content,:class=>"form-control"

  .field
    p
    = f.label :tag, '标签'
    p
    = f.text_area :tag,:class=>"form-control"


  .action
    = f.submit '提交', :class=>'btn btn-primary'




end

app/views/users/_article_list.slim
//h1 =user.id '的博客'
h1

.articlelist
  table
    thead
      tr
        th 标题
        th 正文
        th 创建日期
        th 操作
    tbody
      - articles.each do |article|
        tr
          td =article.title
          td =article.user.name
          td =article.created_at
          th = link_to "编辑", edit_article_path(article.id)

app/views/users/_form.slim
= form_for @user do |f|
  = @user.errors.messages
  .field
    = f.label :name, 'name'
    = f.text_field :name,:class=>"form-control"
  .field
    = f.label :email, 'eMail'
    = f.text_field :email,:class=>"form-control"
  .field
    = f.label :avatar, 'Avatar'
    = f.file_field :avatar,:class=>"form-control"
  /.field
  /  = f.label :password, 'password'
  /  = f.text_field :password
  .field
    = f.radio_button :role, 'admin'
    = f.label :role_admin, 'Admin'
    = f.radio_button :role, 'Pitizen'
    = f.label :role_pitizen, 'Pitizen'
  .action
    = f.submit 'submit', :class=>'btn btn-primary'
end

app/views/users/edit.slim
.container

  = render :partial=>'form'

  = link_to '返回', user_path

app/views/users/index.slim
.container
  ol.breadcrumb
    li
      = link_to '首页','#'
    li.active
      = link_to '用户管理','#'

  .btn-group
    = link_to '创建用户', new_user_path, :class => 'btn btn-primary'




    / .alist
    /   / = render :partial=>"article_list", :locals=>{:article=>Article.where(:user_id=>@user.id)}
    /   = render :partial=>"article_list", :locals=>{:articles=>@articles}
  .row
    .col-md-12
      table.table.table-responsive.table-hover
        thead
          th 用户名
          th 角色
          th 操作
        tbody
          - for user in @users
            tr
              td = user.name
              td = user.role
              td
                = link_to '查看', user_path(user)
      .page
        = paginate @users
      end

app/views/users/new.slim
h1 新建用户
= render :partial=>'form'

app/views/users/show.slim
.container
  ol.breadcrumb
      li
        = link_to '首页','#'
      li
        = link_to '用户管理','#'
      li.active
        = link_to '用户详情','#'


  p
    b 姓名:
    = @user.name
  p
    b eMail:
    = @user.email
  p
    b 头像:
    = image_tag @user.avatar, height:'64'

  p
    b 角色
    = @user.role



  = render :partial=>"article_list", :locals=>{:articles => @user.articles}
  = render :partial=>"article_form", :locals=>{:article=>Article.new(:user_id=>@user.id)}
  = button_to ' 编辑 ', edit_user_path, method: :get
  = button_to ' 删除 ', user_path, method: :delete, data: {confirm: '你确认么？'}
  = link_to ' 返回 ', users_path

app/views/welcome/index.slim
h1 Welcome to my Blog